# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/MOODLE/Vivado_projects/character_recognition/character_recognition.cache/wt [current_project]
set_property parent.project_path I:/MOODLE/Vivado_projects/character_recognition/character_recognition.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo i:/MOODLE/Vivado_projects/character_recognition/character_recognition.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_15.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_15.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/sigContent.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_20.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_20.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_11.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_11.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_12.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_12.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_29.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_29.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_28.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_21.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_10.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_10.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_21.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_19.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_14.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_27.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_13.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_22.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_23.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_26.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_18.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_17.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_25.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_16.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_24.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_16.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_17.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_17.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_15.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_24.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_25.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_19.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_14.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_27.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_22.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_13.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_19.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_28.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_18.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_26.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_10.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_23.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_20.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_11.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_29.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_12.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_20.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_28.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_12.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_28.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_11.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_29.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_27.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_22.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_23.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_18.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_19.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_26.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_10.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_13.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_21.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_14.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_16.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_25.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_24.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_25.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_4.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_15.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_24.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_3.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_23.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_16.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_27.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_1_14.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_3_6.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_22.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_9.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_7.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_21.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_4_2.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_13.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_4_5.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_1.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_1_26.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_8.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_3_0.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/w_2_17.mif
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/b_2_18.mif
}
read_verilog -library xil_defaultlib {
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/axi_lite_wrapper.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/layer_1.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/layer_2.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/layer_3.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/layer_4.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/max_finder.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/include.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/neuron.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/relu.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/sig_rom.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/weight_memory.v
  I:/MOODLE/Vivado_projects/character_recognition/character_recognition.srcs/sources_1/new/zynet.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zynet -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zynet.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zynet_utilization_synth.rpt -pb zynet_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
